### ISSUE TITLE
nested keys ?

### ISSUE THREAD

**Issue by instasck** [RaRe-Technologies/sqlitedict#101]
when trying to use nested dict it won't allow me:
db['first']['second'], what is the proper solution ?

**Comment by piskvorky** [comment]
Not clear what you're asking, closing. Feel free to add more context and tracebacks, then we'll have a look.

**Comment by instasck** [comment]
@piskvorky 
Let me explain.
I would like to create a dict that the keys are nested as so:
db[user] = 'piskvorky'
db[user]['contacts'] = ['s','b'...]
db[user]['social'] = facebook


and so on ...
I can't achive it now.

**Comment by piskvorky** [comment]
Strings do not support assignment: you cannot do `'piskvorky'['contacts'] = ['s', 'b']` in Python.

This is more a Python syntax question, not  a `sqlitedict` question. If you read the tracebacks Python shows you carefully, you'll figure it out.
