### ISSUE TITLE
Not updating the dict for some reason?

### ISSUE THREAD

**Issue by Mradr** [RaRe-Technologies/sqlitedict#115]
So I am a bit confuse on why this isn't working. While I understand that you can't change things in "ram" why does this  not work?

self.settings = SqliteDict( f'database/devices/{id}/{id}.sqlite', tablename=id, autocommit=True )
self.settings.update( copy.deepcopy( default_settings.default_device_settings ) )
self.settings["profile"] = settings < different settings just a {lots of objects} I tried both = and .update
self.settings["profile"]["device_id"] = id < id has to exist other wise the above wouldn't work, but I can confirm there is an entry here
print(self.settings["profile"]["device_id"]) < says this either blank or does not exist. Why though? I updated the entry. Far as I understand it sqlitedict should like this?
 
I understand there is a beware section - but if someone can point me in the right direction to make this work still that be great. I am not sure if I am just falling into the beware section and not understanding how to get out of it.

**Comment by Mradr** [comment]
Ok after a bit more testing it looks like SqliteDict does not support nested dicts past the first key. So for example:
self.settings["profile"] = {"device_id": id} < works fine
self.settings["profile"]["device_id"] = id < does not

**Comment by piskvorky** [comment]
Sqlitedict supports all (pickleable) Python objects, including nested dicts.

Check out the **BEWARE** section in https://github.com/RaRe-Technologies/sqlitedict/#documentation for how to store mutable objects.

**Comment by Mradr** [comment]
You need to update the beware section for more examples.
