### ISSUE TITLE
Maybe this idea can work to update main key and update the object from there

### ISSUE THREAD

**Issue by Mradr** [RaRe-Technologies/sqlitedict#116]
So I hated the automatic response I got from this person.... 

Anyways - working on this more I figure out you can add a little depth to update the parent. While this is just a rough idea - it seem to work from a quick few test runs. Adding support for list should be pretty easy as well same for any other type.

```python
class ActionableDict(dict):
    parent = None
    def __init__(self, initial_dict, parent=None, parent_key=None):
        self.parent = parent
        self.parent_key = parent_key
        for key, value in initial_dict.items():
            if isinstance(value, dict):
                initial_dict[key] = ActionableDict(value, self)
        super().__init__(initial_dict)

    def __setitem__(self, key, value):
        if isinstance(value, dict):
            _value = ActionableDict(value, self)
        else:
            _value = value
        print("You are changing the value of {} to {}!!".format(key, _value))
        super().__setitem__(key, _value)
        self._update_parent()

    def _update_parent(self):
        self.parent[self.parent_key] = self
        print(type(self.parent))

class SqliteDict(DictClass):
    def __getitem__(self, key):
        GET_ITEM = 'SELECT value FROM "%s" WHERE key = ?' % self.tablename
        item = self.conn.select_one(GET_ITEM, (key,))
        if item is None:
            raise KeyError(key)
        item = self.decode(item[0])
        if isinstance(item, dict):
            return ActionableDict(item, self, key)
        return item
```

You need to update the beware section for more examples. Some of the examples around here display the above and thus can confuse the user.

Also, a bit of a mislead to say it supports it... what it does support is the ability to pick objects in a key/value first level. Any deeper and it breaks.

_Originally posted by @Mradr in https://github.com/RaRe-Technologies/sqlitedict/issues/115#issuecomment-668556117_

**Comment by gooseillo** [comment]
@Mradr did you manage to get it to work? I had the same problem to which I got a similar response as you.

**Comment by Mradr** [comment]
The above can work for a set of things. I am sure more can be done to improve it and make it as stable as working with in memory dicts or faster. This was just a rough idea on how it could work.

**Comment by piskvorky** [comment]
Thanks for the suggestion. We will not implement such "nested mutation tracking" in SqliteDict – it's a can of worms.

But if the scenario is useful to you and others, feel free to publish your extension.
