### ISSUE TITLE
How to specify Pickle Version?

### ISSUE THREAD

**Issue by jsutch** [RaRe-Technologies/sqlitedict#121]
When trying to dockerize a project I find that the docker sqlitedict is apparently using pickle5, throwing sqldict errors.  Is there a way to specify a pickleversion on instantiation? No errors on the raw dev environments in OSX and Ubuntu - just within the docker container.

Here's where I setup the database and the call that's failing:
# database
from sqlitedict import SqliteDict
jobsdb = SqliteDict('/var/www/webhook/app/jobs.db', autocommit=True)
def pollnew():
    """
    check for jobs with 'accepted' status
    """
    return [(k) for k, v in jobsdb.items() if v['status'] == 'accepted']

environment:
root@6e951e7b1a72:/var/www/webhook/app# python3 --version
Python 3.8.5
root@6e951e7b1a72:/var/www/webhook/app# uname -a
Linux 6e951e7b1a72 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 GNU/Linux

Here's the error:
Traceback (most recent call last):
  File "/var/www/webhook/app/worker.py", line 327, in <module>
    main_loop()
  File "/var/www/webhook/app/worker.py", line 310, in main_loop
    job_starter()
  File "/var/www/webhook/app/worker.py", line 204, in job_starter
    newjobs = pollnew()
  File "/var/www/webhook/app/worker.py", line 84, in pollnew
    return [(k) for k, v in jobsdb.items() if v['status'] == 'accepted']
  File "/var/www/webhook/app/worker.py", line 84, in <listcomp>
    return [(k) for k, v in jobsdb.items() if v['status'] == 'accepted']
  File "/usr/local/lib/python3.8/site-packages/sqlitedict.py", line 225, in iteritems
    yield key, self.decode(value)
  File "/usr/local/lib/python3.8/site-packages/sqlitedict.py", line 102, in decode
    return loads(bytes(obj))
ValueError: unsupported pickle protocol: 5

**Comment by piskvorky** [comment]
Yes, the default pickle version is `pickle.HIGHEST_PROTOCOL`, so it depends on the Python version where you run.

This means that the place where you **load** your sqlite objects must support at least the same version as the place where you **stored** them.

To change it, you should be able to do:

```python
import sqlitedict
sqlitedict.PICKLE_PROTOCOL = 4  # or whatever your Python supports
```

before storing the objects. The lower the protocol, the less efficient (slower, more space) but also safer with older versions of Python.

Let me know if that fixed it!

**Comment by jsutch** [comment]
That worked, thanks!
