### ISSUE TITLE
how about replace pickle with dill? or at least make it an option?

### ISSUE THREAD

**Issue by mo-han** [RaRe-Technologies/sqlitedict#124]
`Queue` object couldn't be pickled by `pickle`, which would raise:
```python
TypeError: can't pickle _thread.lock objects
```

luckily, [dill](https://github.com/uqfoundation/dill) is API-compatible with `pickle`, and it could pickle (almost) anything in python, including `Queue`

so, could you please add an option for that?

**Comment by piskvorky** [comment]
Serializing locks makes no sense. What is your application? This looks more like a programmer error, changing serialization formats wouldn't help.

**Comment by mo-han** [comment]
> 
> 
> Serializing locks makes no sense

https://stackoverflow.com/a/25411691/7966259

**Comment by piskvorky** [comment]
I know what `dill` is, but I'm unclear why you need it. Can you describe your motivation?

Serializing objects that are fundamentally unserializable (file handles, open streams, locks…) indicates an error in the application layer, in which case masking the problem at the database library layer by replacing pickle with dill would do more harm than good.

**Comment by mo-han** [comment]
@piskvorky 
that stackoverflow answer is not to tell you what `dill` is, but to show there are some people who need to pickle those so called "un-serializable" objects, and which is practicable.
didn't see anyone asking for a motivation in that stackoverflow answer. why would you like to know my motivation so much, when you already had that motivation from others?
even without your help, the patch is quite simple:
```python
import dill
import sqlitedict

sqlitedict.dumps = dill.dumps
sqlitedict.loads = dill.loads
sqlitedict.PICKLE_PROTOCOL = dill.HIGHEST_PROTOCOL
```
no big deal
have a nice day

**Comment by piskvorky** [comment]
Because we do not include patches without a clear motivation.

If dill works for you, great – but in case anyone stumbles on this ticket in the future, mind the caveats above.

**Comment by mo-han** [comment]
```python
def sqlitedict_with_dill():
    import dill
    import sqlitedict
    sqlitedict.dumps = dill.dumps
    sqlitedict.loads = dill.loads
    sqlitedict.PICKLE_PROTOCOL = dill.HIGHEST_PROTOCOL
    return sqlitedict


import queue

sqlitedict = sqlitedict_with_dill()
q = queue.Queue()
q.put(1)
with sqlitedict.SqliteDict('tmp.db', autocommit=True) as sd:
    sd['q'] = q
with sqlitedict.SqliteDict('tmp.db', autocommit=True) as sd:
    print(sd['q'].get() == 1)
```
