### ISSUE TITLE
Cache operation

### ISSUE THREAD

**Issue by ese942** [RaRe-Technologies/sqlitedict#126]
From the description I expected sqlitedict to operate a memory cache.  However it does not: every access to the dict hits the database.  One would expect data would be cached in sqlitedict and only hit the db when needed - at least as a user parameter, if not the default behavior.

E.g. a simple len () request should cache the number of items and return it, rather than a linear scan with SELECT COUNT (*) every time.  Either because only one process accesses the db, so it always has the latest info in memory.  Or because short-term changes are unimportant and recent-ish data is good enough (think of a daily temperature graph with temp readings every minute, where the result barely changes if the last few readings aren't available ).  Data can be synced with the db periodically according to user preference.

Does anyone know how to achieve this?  Map a simple in-memory dict to sqlite, backed by syncs periodically or as-needed (on write)?  Doesn't seem possible with this project.  If not, any similar projects that fit the bill?  Don't need or want something heavyweight like SQLAlchemy or SQLObject.
Thanks.

**Comment by piskvorky** [comment]
You are correct – sqlitedict is not a cache. It's a persistent dict backed by SQLite.

I think you could add your own "caching" layer of application logic on top of sqlitedict, with periodic syncing or whatever. Closing here.

**Comment by ed2050** [comment]
> I think you could add your own "caching" layer of application logic on top of sqlitedict, with periodic syncing, or any other functionality you like.

I could also program a Motorola 68000 hooked up to drum memory with nothing but a piece of wool and an iron needle.  The point isn't what I can do.  The point is what's the best approach.

Happy holidays to all the kind, helpful people out there... wherever they are.
