### ISSUE TITLE
the big one

### ISSUE THREAD

**Issue by NitinNR** [RaRe-Technologies/sqlitedict#133]
pair = {"name":"","age":""}

mydict["key"] = pair

mydict["key"]["name"] = "changed'

not able to assign.please tell me how this works!

**Comment by piskvorky** [comment]
See the `Beware` section in the README: https://github.com/RaRe-Technologies/sqlitedict#documentation

**Comment by NitinNR** [comment]
> Please see the `Beware` section in the README: https://github.com/RaRe-Technologies/sqlitedict#documentation

pair = {"name":"","age":""}

mydict["key"] = pair

mydict["key"]["name"] = "changed'

not able to assign.please tell me how this works!

please tell me how i can achieve this?
