### ISSUE TITLE
Context manager operation thread-safe?

### ISSUE THREAD

**Issue by teetone** [RaRe-Technologies/sqlitedict#145]
Hello, I was looking through the documentation and was wondering if the following code was thread-safe without any additional locks:

```
from sqlitedict import SqliteDict

with SqliteDict(self.cache_path) as cache_dict:
     cache_dict[key] = response
     cache_dict.commit()
```

**Comment by piskvorky** [comment]
The code inside the context manager (within `with`, one `SqliteDict` database connection) is thread-safe.

But opening multiple connections (multiple `with` blocks concurrently) – not so much. The underlying database engine, SQLite, offers only limited support for this (see [FAQ](https://sqlite.org/faq.html#q5). Definitely not in scope for `sqlitedict`, which handles thread-safety within a single process, single `SqliteDict` object = database connection.
