### ISSUE TITLE
v2 Release Not Completely Documented and Missing from Github

### ISSUE THREAD

**Issue by Justintime50** [RaRe-Technologies/sqlitedict#150]
It appears that this package had v2 released on PyPI but not on GitHub nor does the CHANGELOG reflect that and the build is failed on the master branch. Is v2 stable and actually released? If so, can the GitHub release reflect this and the CHANGELOG get updated to clarify?

**Comment by mpenkov** [comment]
Yes, it's stable. We forgot to publish the release on github. Please go ahead and use it.

https://github.com/RaRe-Technologies/sqlitedict/releases/tag/2.0.0

The test failures were unrelated - it was an obsolete test.
