### ISSUE TITLE
Use of deprecated threading.Thread.setDaemon raises warning in python 3.10

### ISSUE THREAD

**Issue by biostu24** [RaRe-Technologies/sqlitedict#156]
Since python 3.10, setDaemon from threading.Thread has been deprecated ([see this link](https://docs.python.org/3/library/threading.html#threading.Thread.setDaemon)). When using SqliteDict in python 3.10, a warning raised.

These code should be updated to prevent this warning.

**Comment by piskvorky** [comment]
@biostu24 thanks – can you open a PR?

**Comment by biostu24** [comment]
@piskvorky I will do, I have a fix for this issue
