### ISSUE TITLE
Can I write to a sqlite database without knowing the row number

### ISSUE THREAD

**Issue by pranavlal** [RaRe-Technologies/sqlitedict#172]
I am a new user of SqliteDict. 
I am confused about one part.  In my program, several threads will write to the same table. I do not know the row number so cannot do
`product[1]={"name":value}`

Can I write to the database without specifying any numbers?

**Comment by piskvorky** [comment]
Sqlitedict acts as a dict, and the keys are expected to be strings. See the README for examples: https://github.com/RaRe-Technologies/sqlitedict#usage
