### ISSUE TITLE
Python 3.6 support: sqlite3.OperationalError: Safety level may not be changed inside a transaction

### ISSUE THREAD

**Issue by bit** [RaRe-Technologies/sqlitedict#58]
fails in python3.6 with

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File ".../site-packages/sqlitedict.py", line 371, in run
    cursor.execute('PRAGMA synchronous=OFF')
sqlite3.OperationalError: Safety level may not be changed inside a transaction

**Comment by tmylk** [comment]
How can this be reproduced? It doesn't come up in Travis Python 3.6 tests

**Comment by bit** [comment]
creating a new instance with autocommit=False triggers this here:

`test = SqliteDict(autocommit=False)`

**Comment by bit** [comment]
Looks like travis still does not fail, even without a new test, `make test-all` fails here on Arch Linux and Debian/unstable with python3.6 and sqlite 3.16.2

**Comment by tmylk** [comment]
Let's check sqlite version used in Travis in https://github.com/RaRe-Technologies/sqlitedict/pull/62

**Comment by tmylk** [comment]
Hmm the sqlite version in travis is really old.

**Comment by bit** [comment]
Also fails with Ubuntu 17.04 (sqlite 3.15.2).
[Here a Dockerfile](https://gist.github.com/bit/e602701ce96a11a78cdc3ce36c2a3e61) to test with Ubuntu 17.04, possibly something like that can be added to travis

**Comment by bit** [comment]
Also fails in Ubuntu 16.06 (sqlite 3.14.1 / Python 3.6)
