### ISSUE TITLE
Question: Issues with json encode? Also, is it multiprocess safe?

### ISSUE THREAD

**Issue by Jwink3101** [RaRe-Technologies/sqlitedict#66]
Sorry, not  a bug, just a question. I am very interested in this tool for a data store on a tiny web app. I do not want to just use JSON files since I want it to be thread-safe (even though it won't really ever be an issue). Is this safe for multiple processes to try to write it? I know multiple threads work.

Anyway, is there a downside to using `json.dumps` and `json.loads` for the encoder and decoder? Is it just a bit slower?

Thanks!

**Comment by tmylk** [comment]
Hi,

About multi-process write. Sqlite locks the file for writing for other processes while one process is writing to it. `sqlite3` and `sqlitedict` default behaviour is to wait 5 seconds for the lock to go away which is usually enough.

Using `json` is actually faster than pickle/compression, the only downside is using more space.

Feel free to re-open if you have more questions on the same topic.

**Comment by piskvorky** [comment]
Yes, multiple processes for the same database are a bad idea with SQLite (not sqlitedict's fault).

Like @tmylk says, `json` may be faster but unlike pickle, it cannot handle any object. For Python objects that cannot be represented in JSON, you'll get an error.
