### ISSUE TITLE
Maximum number of keys and multiple dicts in a database?

### ISSUE THREAD

**Issue by ayaanhossain** [RaRe-Technologies/sqlitedict#68]
Hi, I was wondering about (a) what is the maximum number of keys that can be used in sqlitedict? and (b) how to use to use multiple dicts in the same database (that's a feature you listed in the readme I guess) and what is the maximum number of such dicts that can be present in the database?

Typically, is it possible to have like 20 billion keys whose values are lists of integers in a single dict? Also can I have hundreds of such dicts in the same db file?

Thanks,
Ayaan

**Comment by menshikh-iv** [comment]
Hi @ayaanhossain 
(a) All limitation from sqlite, look at [this page](https://sqlite.org/limits.html) **Maximum Number Of Rows In A Table** and **Maximum Database Size**
(b) Yes, it's possible through set `tablename` parameter, looks at example
```python
from sqlitedict import SqliteDict

fname = "file.sqlite"
dicts = ["first", "second"]  # two names for our dicts

with SqliteDict(filename=fname, tablename=dicts[0], autocommit=True) as dct:
# Write data to 'first' dict
    dct[1] = 100
    dct[2] = 200

with SqliteDict(filename=fname, tablename=dicts[1], autocommit=True) as dct:
# Write data to 'second' dict
    dct[1] = 123
    dct[2] = 456
    dct[3] = 3

# Read all dicts
for dictionary_name in dicts:
    with SqliteDict(filename=fname, tablename=dictionary_name) as dct:
        print(dictionary_name, dct.items())

"""
Output:
('fist', [('1', 100), ('2', 200)])
('second', [('1', 123), ('2', 456), ('3', 3)])
"""
```

**Comment by ayaanhossain** [comment]
Thanks. Learnt a lot.
