### ISSUE TITLE
Retrieving value of a specific key is slow

### ISSUE THREAD

**Issue by MiladAlshomary** [RaRe-Technologies/sqlitedict#75]
I have a sqllite dictionary contains 4.2 million key. Each value is a list of pyspark [sparsevector](https://spark.apache.org/docs/1.1.0/api/python/pyspark.mllib.linalg.SparseVector-class.html)

Trying to retrieve the value of a specific key takes around 3 seconds! any known issue related?

**Comment by piskvorky** [comment]
@MiladAlshomary how large is that value? How long does pickling it take? (sqlitedict uses pickle internally to serialize the values)

**Comment by MiladAlshomary** [comment]
@piskvorky 
The values are not big. they are less than 1 kbyte. One thing I was wondering about, if the created sqllite table has already an index over they key column?

**Comment by ownport** [comment]
@MiladAlshomary it should be according to
```
MAKE_TABLE = 'CREATE TABLE IF NOT EXISTS "%s" (key TEXT PRIMARY KEY, value BLOB)' % self.tablename
```

**Comment by piskvorky** [comment]
Sure, it does. A key-value store without an index on key wouldn't be very useful :-)

If you send a minimal reproducing example, we'll have a look. Thanks.

**Comment by MiladAlshomary** [comment]
Hi, it seems like the issue is not reproducible. Something went wrong with the db connection I believe. Now its working properly, retrieving the value of a key takes milli seconds

**Comment by menshikh-iv** [comment]
@MiladAlshomary aha, OK, thanks for the information.
