### ISSUE TITLE
Nested dictionaries not supported

### ISSUE THREAD

**Issue by sshindesiddesh** [RaRe-Technologies/sqlitedict#80]
Is there any plan to support the persistence of nested dictionaries?

E.g.
mydict = SqliteDict('./my_db.sqlite', autocommit=True)
newdict = dict()
dict['key-1'] = 'value-1'
mydict['newdict'] = newdict

- Untill here everything is persistent. But if I modify the internal dictionary now, it is not persisted.

newdict1 = mydict['newdict']
newdict1['key-2'] = 'value-2'

But this new key ('key-2') is not reflected in the database.

**Comment by piskvorky** [comment]
See the **Beware** section in README.
