### ISSUE TITLE
Stuck at commit?

### ISSUE THREAD

**Issue by chengguangnan** [RaRe-Technologies/sqlitedict#83]
Sorry I can't figure out a reproducible example for this. But in a real world project, whenever 100 keys were added, reopen the Sqlitedict will stuck at the commit below.

```
        logger.info("opening Sqlite table %r in %s" % (tablename, filename))
        MAKE_TABLE = 'CREATE TABLE IF NOT EXISTS "%s" (key TEXT PRIMARY KEY, value BLOB)' % self.tablename
        logger.info(MAKE_TABLE)
        self.conn = self._new_conn()
        logger.info("execute")
        self.conn.execute(MAKE_TABLE)
        logger.info("commit")
        self.conn.commit()
```

I tried to reproduce this in an isolated example, but the problem doesn't happen in this example. But I attached it below anyway. My values contains nested dictionaries and about 30 fields, about 180K on disk. I switched to `shelve` because I have no idea what could be the cause. JFYI.

```
import sqlitedict


def ss():
    return sqlitedict.SqliteDict("cache.sqlite", autocommit=True)

for i in range(3000000):
    key = f"key-{i}"
    print(key)
    with ss() as sd:
        sd[key] = dict(foo=1, nested=dict(bar=1))
```

**Comment by piskvorky** [comment]
@chengguangnan what is the actual error? What does "stuck" mean exactly, what do you see? How is the first code snippet you posted connected to the error? Thanks!

**Comment by chengguangnan** [comment]
@piskvorky , these is no error message at all. The program has not further output for a couple hours or days maybe. And there are no stack trace printed if I Control+C.  

The first code snippet is copied from sqlitedict.py, I added a couple logger there to figure out at which step the problem happened, it happened after `logger.info("commit")`.

**Comment by chengguangnan** [comment]
Oh, I see, it's blocked here:

```
    def select(self, req, arg=None):
        """
        Unlike sqlite's native select, this select doesn't handle iteration efficiently.

        The result of `select` starts filling up with values as soon as the
        request is dequeued, and although you can iterate over the result normally
        (`for res in self.select(): ...`), the entire result will be in memory.
        """
        logger.info("inside select")
        res = Queue()  # results of the select will appear as items in this queue
        logger.info("before execute")
        self.execute(req, arg, res)
        while True:
            logger.info("before get")
            rec = res.get()  # <---------- blocked here upon SqliteDict open
            logger.info("after get")
            self.check_raise_error()
            if rec == '--no more--':
                break
            yield rec
```
````
2018-10-18 06:13:36 INFO [mailchimp.py:119] Post returned
2018-10-18 06:13:36 INFO [mailchimp.py:139] SqliteDict
2018-10-18 06:13:36 INFO [sqlitedict.py:171] opening Sqlite table 'unnamed' in cache.sqlite
2018-10-18 06:13:36 INFO [sqlitedict.py:175] commit
2018-10-18 06:13:36 INFO [sqlitedict.py:527] inside commit
2018-10-18 06:13:36 INFO [sqlitedict.py:529] going to select_one --commit --
2018-10-18 06:13:36 INFO [sqlitedict.py:521] inside select_one
2018-10-18 06:13:36 INFO [sqlitedict.py:505] inside select
2018-10-18 06:13:36 INFO [sqlitedict.py:507] before execute
2018-10-18 06:13:36 INFO [sqlitedict.py:510] before get
```

**Comment by chengguangnan** [comment]
Ha, I know what's going on. The problematic call was inside a __del__ function upon program exit. I guess the some sqlitedict internal stuff has been disposed at that time?  

I was trying to save unsaved content in the __del__ function. Maybe not a good place to do that.

**Comment by menshikh-iv** [comment]
@chengguangnan more safe way for "free" some resources is [context manager](https://docs.python.org/3/library/contextlib.html), like

```python
with MyResource() as resource:
    # make what's needed
```

also, good post about it - https://eli.thegreenplace.net/2009/06/12/safely-using-destructors-in-python/
