### ISSUE TITLE
Feature Request: Store nested dictionaries as new tables

### ISSUE THREAD

**Issue by Jwink3101** [RaRe-Technologies/sqlitedict#84]
This is both a feature request and to get an idea if people would be interested. Essentially, if you have a sub-dictionary that is not at the top level, the entire thing also has to be encoded.

I propose that when a user *explicitly* says to, make a subdictionary a new table as well. The idea is still very rough, but essentially modify the main class to be able to have a parent class (and therefore share the connection). Then, add a function that creates a new `SqliteDict` child instance. The table name should either something like `tablename + uuid4()`. Then this new object will behave just like its own `SqliteDict`. The only difference will be when you `__setitem__` (or `update`) a child instance, it will instead make a pointer to that table and when you `__getitem__` it will recreate it and when you `__delitem__`, it will drop it.

I *think* autocommit should still work and carry through.

A final idea along the same vein (though certainly harder to do) is to make a list-like object that behaves the same way. Use a sub `SqliteDict` under the hood but allow for storage. THis may be farther fetched.

Any ideas?

**Comment by menshikh-iv** [comment]
ping @piskvorky

**Comment by Jwink3101** [comment]
I got this working but I forget how. I remember there being some major hurdles and I think the workarounds required some major tweaks and broke some other (edge cases presumably)

**Comment by piskvorky** [comment]
-1 on this. I can see the use-case, but SqliteDict aims to be small and simple, a wrapper for Sqlite that's easy to reason about. Nested tables would imply too much magic under the hood, sorry.

**Comment by instasck** [comment]
You can try this:
```
from collections import defaultdict
from sqlitedict import SqliteDict


class nested_dict_sqlite(defaultdict):
    'like defaultdict but default_factory receives the key'

    def __missing__(self, key):
        self[key] = value = self.default_factory(key)
        return value


dicts = nested_dict_sqlite(lambda table: SqliteDict('dicts.sqlite3', table, 'c', True))
dicts['dict1']['x'] = 1
dicts['dict2']['y'] = 2

print(dicts['dict1']['x'])
print(dicts['dict2']['y'])
print(dicts['dict2']['yy'])
```

not best solution but let you work 2D
