### ISSUE TITLE
Comparison with Python Disk Cache

### ISSUE THREAD

**Issue by grantjenks** [RaRe-Technologies/sqlitedict#87]
Hi, I'm the author of the [Python Disk Cache](https://github.com/grantjenks/python-diskcache/) project and it seems like there's a lot of overlap with sqlitedict. I was interested in doing a feature comparison and started researching [features](https://github.com/grantjenks/python-diskcache/issues/82).

I'd love to get your feedback on the diskcache project.

**Comment by menshikh-iv** [comment]
Hi @grantjenks sounds good :+1:

**Comment by grantjenks** [comment]
I did a little micro-benchmarking:

```
$ python -m IPython
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import diskcache                                                                                                

In [2]: c1 = diskcache.FanoutCache('/tmp/fanout')                                                                       

In [3]: %timeit c1['test'] = 10                                                                                         
133 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [4]: %timeit c1['test']                                                                                              
18.2 µs ± 148 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [5]: !pip install sqlitedict                                                                                         
Collecting sqlitedict
  Using cached https://files.pythonhosted.org/packages/0f/1c/c757b93147a219cf1e25cef7e1ad9b595b7f802159493c45ce116521caff/sqlitedict-1.6.0.tar.gz
Installing collected packages: sqlitedict
  Running setup.py install for sqlitedict ... done
Successfully installed sqlitedict-1.6.0
You are using pip version 18.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [6]: import sqlitedict                                                                                               

In [7]: c2 = sqlitedict.SqliteDict('/tmp/sqlitedict1', autocommit=True)                                                 

In [8]: %timeit c2['test'] = 10                                                                                         
244 µs ± 2.55 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [9]: %timeit c2['test']                                                                                              
299 µs ± 3.97 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [10]: c3 = sqlitedict.SqliteDict('/tmp/sqlitedict1', autocommit=False)                                               

In [11]: %timeit c3['test'] = 10                                                                                        
227 µs ± 2.93 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [12]: %timeit c3['test']                                                                                             
272 µs ± 5.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

And it seems that DiskCache is quite a bit faster. That surprised me because all DiskCache operations are atomic and with SqliteDict's `autocommit=False` option I thought it would run faster. Before I publish a comparison, can you observe the same? Am I using SqliteDict correctly in those benchmarks?

The only functional difference I can spot between our projects is the autocommit option which I would rather not implement in DiskCache. (Seems like it would be too easy to forget to "close" a dictionary and it may interfere with other threads/processes.) But I wonder, could you just use Disk Cache instead?

**Comment by piskvorky** [comment]
Hey @grantjenks , thanks for the benchmark.

Sqlitedict's mission is to be a stable, thread-safe wrapper for the built-in sqlite DB. Sqlitedict's purpose is not performance (it uses plain pickle under the hood to serialize/deserialize keys and values). I'm actually surprised it's so close in performance to an optimized library.

I'm gonna close this now, but please update us with comparisons. I can see how DiskCache could be a superior choice for some workflows.
