### ISSUE TITLE
To create value as non-blob type

### ISSUE THREAD

**Issue by occoder** [RaRe-Technologies/sqlitedict#88]
Hi, 
I notice that all the values created and entered into sqlite file are of type BLOB.
`MAKE_TABLE = 'CREATE TABLE IF NOT EXISTS "%s" (key TEXT PRIMARY KEY, value BLOB)' % self.tablename`
When I need to use a GUI tool like https://github.com/sqlitebrowser/sqlitebrowser to check and adjust the table content, the value can not be shown appropriately.
If possible, how to customize the vaule type?
Thanks.

**Comment by occoder** [comment]
It seems following scheme allows me to do that.
`mydict = SqliteDict('./my_db.sqlite', encode=json.dumps, decode=json.loads)`

**Comment by menshikh-iv** [comment]
@occoder as I see, you resolve your problem, so, I close that.
