### ISSUE TITLE
Multi thread example

### ISSUE THREAD

**Issue by sionking** [RaRe-Technologies/sqlitedict#89]
I trigger 10 thread of workers that fill the userDb, without any locking mechanisem

```
def worker(name, value):
    userDb[name] = value

def sync():
    userDb.commit()

userDb = SqliteDict('./usernames.sqlite', encode=json.dumps, decode=json.loads, autocommit=False)
```

I also triger sync thread every 5 minutes, is it safe to do so ?

**Comment by menshikh-iv** [comment]
@sionking not really sure that this is safe, @piskvorky?

**Comment by piskvorky** [comment]
It's safe to the degree Sqlite itself supports it. All SqliteDict does is serialize the requests from multiple threads into a single queue, executing them one after the other. It adds thread safety, not extra performance.

**Comment by leahcornelius** [comment]
@piskvorky Im guessing the order of the queue is somewhat unpredictable? If I have 10 threads all writing to the same key (and say some of them happen to write at the exact same time) I don't know the order of which they will be executed?

**Comment by piskvorky** [comment]
Correct.
