### ISSUE TITLE
splitting by key into multiple sqlite files

### ISSUE THREAD

**Issue by notestaff** [RaRe-Technologies/sqlitedict#91]
To improve concurrent access, it would help to split the sqlite database file into multiple files, with the key hash determining which file stores the full key-value mapping for the key.  Then concurrent writes would be ok as long as the keys are assigned to different sqlite database files.  You'd initialize sqlitedict not with a file but with a directory, and under that directory would create the sqlite db files.

**Comment by piskvorky** [comment]
That sounds useful but out of scope for `sqlitedict`, sorry.
