### ISSUE TITLE
disk read/write rise and application get stuck.

### ISSUE THREAD

**Issue by sionking** [RaRe-Technologies/sqlitedict#92]
when the system is busy with multiple thread writing to the sql dict sometimes I get the following beehive:
![image](https://user-images.githubusercontent.com/7851877/53668732-6daacf00-3c7d-11e9-9c27-3b2dac6c1660.png)

I don't think it is my application since it is only happens when many threads do lots of read/write to disk using sqlitedict.

any suggestions ? I thought of schedule "sync" writing to disk instead of commit every operation.

**Comment by instasck** [comment]
Seems like a bed server disk, I use ggoogle cloud and no issue.

**Comment by piskvorky** [comment]
OK. Thanks for following up.
