### ISSUE TITLE
Fix license

### ISSUE THREAD

**Issue by r-barnes** [RaRe-Technologies/sqlitedict#98]
An Apache license is used by the project, but not detected by Github, which views it as being a custom license. If the license file could be changed so that Github recognizes it as Apache that'd make it easier to figure out licensing issues.

**Comment by piskvorky** [comment]
Sounds like a good idea. @mpenkov WDYT?

**Comment by mpenkov** [comment]
No objections. @r-barnes are you able to make a PR?

**Comment by r-barnes** [comment]
Yes, see Pull Request #99

**Comment by mpenkov** [comment]
Closed via #99
